# Generated by Django 3.1.5 on 2021-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='本ジャンルを入力してください(SF,古典)', max_length=200)),
            ],
        ),
    ]
